### ISSUE TITLE
Python version(s)?

### ISSUE THREAD

**Issue by danbri** [EvolutionGym/evogym-design-tool#1]
What version(s) of Python should this work with? Trying on Chromebook, with 

> pip install -r requirements.txt

(which runs fine) and then

> python main.py

With Python 3.8 I get

`Traceback (most recent call last):
  File "src/main.py", line 4, in <module>
    import gui
  File "/home/danbri/ ... /evogym-design-tool/src/gui.py", line 3, in <module>
    from ttkbootstrap import Style
  File "/opt/miniconda3/lib/python3.8/site-packages/ttkbootstrap/__init__.py", line 3, in <module>
    from ttkbootstrap.widgets import *
  File "/opt/miniconda3/lib/python3.8/site-packages/ttkbootstrap/widgets.py", line 13, in <module>
    from ttkbootstrap.dialogs import Querybox
  File "/opt/miniconda3/lib/python3.8/site-packages/ttkbootstrap/dialogs.py", line 15, in <module>
    from tkinter import _get_default_root
ImportError: cannot import name '_get_default_root' from 'tkinter' (/opt/miniconda3/lib/python3.8/tkinter/__init__.py)`

**Comment by danbri** [comment]
If I comment out the tkinter import in /opt/miniconda3/lib/python3.8/site-packages/ttkbootstrap/dialogs.py

i.e. 

> #from tkinter import _get_default_root

It seems to run

**Comment by Evolutionary-Intelligence** [comment]
According to [ __ pycache __ ](https://github.com/EvolutionGym/evogym-design-tool/tree/main/src/__pycache__), it seems to use Python 3.7. @danbri

**Comment by jagdeepsb** [comment]
Hello @danbri! Thanks for your interest in EvoGym. If you haven't resolved the issue yet, I think there might be a problem with conflicting package versions. 

I've added package versions to `requirements.txt` and also added a `environment.yml` file from which you can create a conda environment -- see the README for installation instructions. 

Please let me know if this resolves your issue!

**Comment by danbri** [comment]
thanks! I have not had a chance to test this, but I have no ongoing problems so please close the issue if you like.
