### ISSUE TITLE
AttributeError: module 'glfw' has no attribute 'get_monitor_workarea'

### ISSUE THREAD

**Issue by Yuxing-Wang-THU** [EvolutionGym/evogym-design-tool#2]
Hi, I use python3.7 and I run the command  'python main.py', then I got this: 

AttributeError: module 'glfw' has no attribute 'get_monitor_workarea'

I have tried to reinstall the glfw, but not work. How do I solve this problem?

Happy new year !!

**Comment by jagdeepsb** [comment]
Hi @Yuxing-Wang-THU! Thanks for your interest in EvoGym. If you haven't resolved the issue yet, I think there might be a problem with conflicting package versions.

I've added package versions to `requirements.txt` and also added a `environment.yml` file from which you can create a conda environment -- see the README for installation instructions.

Please let me know if this resolves your issue!

**Comment by Yuxing-Wang-THU** [comment]
> Hi @Yuxing-Wang-THU! Thanks for your interest in EvoGym. If you haven't resolved the issue yet, I think there might be a problem with conflicting package versions.
> 
> I've added package versions to `requirements.txt` and also added a `environment.yml` file from which you can create a conda environment -- see the README for installation instructions.
> 
> Please let me know if this resolves your issue!


Hi, my problem has been addressed, there was something wrong with my glfw package, thank you very much!
Btw,  will there be a new version released in the future? Like OpenAI Gym, which includes many interesting tasks. I am very excited. If possible, I would also like to join you to maintain this platform.

**Comment by jagdeepsb** [comment]
Glad your issue was resolved!
Yes, this repo currently only contains the design tool, but we are releasing the rest of the code soon! 
That would be great, feel free to reach out over email [jagdeep _at_ mit.edu] so we can talk more 😄
